
USE BusinessDataModelDataset;
GO 
/*
These variables will be passed as parameters from the script activity.
Ensure that these declarations remain in the script activity. Otherwise the string length will be limited to 4000 characters.
Also ensure that the string variables declared below are of type varchar.
Otherwise, if using nvarchar, the dynamic sql length will be limited to 4000 characters due to an implicit conversion (varchar to nvarchar) made during the string concatination.
*/

DECLARE @CuratedContainerName varchar(255) = 'curated'
------------------------------------------------------------------------------------------------------
--Copy and paste from below into the script activity. Uncomment variable declaration section.
/*
DECLARE @CuratedContainerName varchar(255) = @CuratedContainerName_Input
*/

--Do not convert this to nvarchar as nvarchar limits string length to 4000 characters whereas maximum length for varchar type is 8000.
DECLARE @DynamicSQL varchar(8000)

--B2C_Customer
SET @DynamicSQL = 'CREATE OR ALTER VIEW [dbo].[B2C_Customer] AS
SELECT
Contact_Reference,
Global_Account_Number,
Title,
First_Name,
Last_Name,
Full_Name,
Local_Language_First_Name,
Local_Language_Last_Name,
Email_Address,
Exam_Results_By_SMS_YN,
Important_Information_By_SMS_YN,
Legal_Flag,
Marketing_YN,
Offers_From_Third_Parties_YN,
Job_Title,
Start_Date,
Date_Of_Birth,
Membership_Date,
Fellow_Date,
Lifetime_Member_Date,
Affiliate_Date,
Student_Earliest_Start_Date,
Readmitted_Date,
Fellow_Due_Date,
Long_Term_Date,
Graduation_Date,
Designation,
Gender,
ISO_Code,
Country,
Nationality,
Phone_Number,
SQA_Eligible_date,
Unique_Learner_Number,
ACCA_Employer_Data_Sharing_Consent_YN,
Employment_Status,
Chinese_Customers_Data_Sharing_Consent_YN,
JES_Data_Sharing_Consent_YN,
Employer,
Primary_Role_Type,
Primary_Role_Group,
Primary_Role_Relationship,
Primary_B2C_Role_History_SK ,
Primary_Role_Start_Date,
Primary_Role_Status,
Primary_Qual_Group,
Preferred_Contact_Method,
Start_Date_Year,
CreatedOn,
ModifiedOn,
Customer_Balance_In_Transaction_Currency,
Customer_Balance_In_Reporting_Currency,
Customer_Overdue_Balance_In_Transaction_Currency,
Customer_Overdue_Balance_In_Reporting_Currency,
D365CE_ContactID
FROM OPENROWSET (
    BULK ''' + @CuratedContainerName + '/BusinessDataModelDataset/B2C/Customer/B2C_Customer/'',
    DATA_SOURCE = ''DataLakeDataSource'',
    FORMAT = ''delta''
) WITH (
Contact_Reference VARCHAR(100),
Global_Account_Number VARCHAR(160),
Title VARCHAR(4000),
First_Name VARCHAR(100),
Last_Name VARCHAR(100),
Full_Name VARCHAR(160),
Local_Language_First_Name VARCHAR(100),
Local_Language_Last_Name VARCHAR(100),
Email_Address VARCHAR(100),
Exam_Results_By_SMS_YN VARCHAR(100),
Important_Information_By_SMS_YN VARCHAR(100),
Legal_Flag VARCHAR(4000),
Marketing_YN VARCHAR(100),
Offers_From_Third_Parties_YN VARCHAR(100),
Job_Title VARCHAR(100),
Start_Date DATE,
Date_Of_Birth DATE,
Membership_Date DATE,
Fellow_Date DATE,
Lifetime_Member_Date DATE,
Affiliate_Date DATE,
Student_Earliest_Start_Date DATE,
Readmitted_Date DATE,
Fellow_Due_Date DATE,
Long_Term_Date DATE,
Graduation_Date DATE,
Designation VARCHAR(100),
Gender VARCHAR(4000),
ISO_Code VARCHAR(100),
Country VARCHAR(100),
Nationality VARCHAR(100),
Phone_Number VARCHAR(100),
SQA_Eligible_date DATE,
Unique_Learner_Number VARCHAR(100),
ACCA_Employer_Data_Sharing_Consent_YN VARCHAR(100),
Employment_Status VARCHAR(100),
Chinese_Customers_Data_Sharing_Consent_YN VARCHAR(100),
JES_Data_Sharing_Consent_YN VARCHAR(100),
Employer VARCHAR(1000),
Primary_Role_Type VARCHAR(100),
Primary_Role_Group VARCHAR(100),
Primary_Role_Relationship VARCHAR(100),
Primary_B2C_Role_History_SK VARCHAR(100),
Primary_Role_Start_Date DATE,
Primary_Role_Status VARCHAR(100),
Primary_Qual_Group VARCHAR(100),
Preferred_Contact_Method VARCHAR(4000),
Start_Date_Year INT,
CreatedOn DATETIME,
ModifiedOn DATETIME,
Customer_Balance_In_Transaction_Currency DECIMAL(32,6),
Customer_Balance_In_Reporting_Currency DECIMAL(32,6),
Customer_Overdue_Balance_In_Transaction_Currency DECIMAL(32,6),
Customer_Overdue_Balance_In_Reporting_Currency DECIMAL(32,6),
D365CE_ContactID VARCHAR(100)
) AS [result]'
EXEC (@DynamicSQL)

--B2C_Practical_Experience
SET @DynamicSQL = 'CREATE OR ALTER VIEW [dbo].[B2C_Practical_Experience] AS
SELECT
    B2C_Practical_Experience_SK,
    Contact_Reference,
    Practical_Experience_Pathway,
    Approved_Employer_Import_Flag,
    Approved_Employer_Role_Flag_Count,
    Current_Roles_Hours_Per_Week,
    Employer_Count,
    Employment_Status,
    Essential_Objective_Approved_Count,
    Essential_Objective_Completed_Count,
    Essential_Objective_Exempt_Count,
    Essential_Objective_Started_Count,
    Exempt_Role_Status,
    First_Trainee_Login_Date,
    First_Update_Date,
    First_Update_Date_Year,
    Last_Trainee_Login_Date,
    Last_Update_Date,
    Number_Of_Months_Remaining,
    Objective_1_Element_Count,
    Objective_1_State,
    Objective_1_State_Date,
    Objective_2_Element_Count,
    Objective_2_State,
    Objective_2_State_Date,
    Objective_3_Element_Count,
    Objective_3_State,
    Objective_3_State_Date,
    Objective_4_Element_Count,
    Objective_4_State,
    Objective_4_State_Date,
    Objective_5_Element_Count,
    Objective_5_State,
    Objective_5_State_Date,
    Objective_6_Element_Count,
    Objective_6_State,
    Objective_6_State_Date,
    Objective_7_Element_Count,
    Objective_7_State,
    Objective_7_State_Date,
    Objective_8_Element_Count,
    Objective_8_State,
    Objective_8_State_Date,
    Objective_9_Element_Count,
    Objective_9_State,
    Objective_9_State_Date,
    Objective_10_Element_Count,
    Objective_10_State,
    Objective_10_State_Date,
    Objective_11_Element_Count,
    Objective_11_State,
    Objective_11_State_Date,
    Objective_12_Element_Count,
    Objective_12_State,
    Objective_12_State_Date,
    Objective_13_Element_Count,
    Objective_13_State,
    Objective_13_State_Date,
    Objective_14_Element_Count,
    Objective_14_State,
    Objective_14_State_Date,
    Objective_15_Element_Count,
    Objective_15_State,
    Objective_15_State_Date,
    Objective_16_Element_Count,
    Objective_16_State,
    Objective_16_State_Date,
    Objective_17_Element_Count,
    Objective_17_State,
    Objective_17_State_Date,
    Objective_18_Element_Count,
    Objective_18_State,
    Objective_18_State_Date,
    Objective_19_Element_Count,
    Objective_19_State,
    Objective_19_State_Date,
    Objective_20_Element_Count,
    Objective_20_State,
    Objective_20_State_Date,
    Objective_21_Element_Count,
    Objective_21_State,
    Objective_21_State_Date,
    Objective_22_Element_Count,
    Objective_22_State,
    Objective_22_State_Date,
    Objective_23_Element_Count,
    Objective_23_State,
    Objective_23_State_Date,
    Objective_24_Element_Count,
    Objective_24_State,
    Objective_24_State_Date,
    Optional_Objectives_Remaining,
    Progress_Recorded,
    Progress_Approved,
    Required_Objectives_Available,
    Role_Count,
    Time_Calculated_Approved_Employer,
    Time_Calculated_On_Role,
    Time_Units_Claimed,
    Time_Units_Claimed_Student_Affiliate,
    Time_Units_Approved,
    Time_Units_Approved_Student_Affiliate,
    Total_Objectives_Remaining,
    Zero_Percent_Relevant_Role,
    Member_Active_Pathway_ID,
    Optional_Objectives_Approved_Count,
    Optional_Objectives_Exempt_Count,
    Optional_Objectives_Progress_Count,
    Optional_Objectives_Started_Count,
    ingestedDate,
    AXIA_AccaID
FROM OPENROWSET (
    BULK '''+@CuratedContainerName+'/BusinessDataModelDataset/B2C/Customer/B2C_Practical_Experience/'',
    DATA_SOURCE = ''DataLakeDataSource'',
    FORMAT = ''delta''
) 
WITH 
(
    B2C_Practical_Experience_SK  VARCHAR(100),
    Contact_Reference VARCHAR(100),
    Practical_Experience_Pathway VARCHAR(100),
    Approved_Employer_Import_Flag VARCHAR(100),
    Approved_Employer_Role_Flag_Count INT,
    Current_Roles_Hours_Per_Week INT,
    Employer_Count INT,
    Employment_Status VARCHAR(100),
    Essential_Objective_Approved_Count INT,
    Essential_Objective_Completed_Count INT,
    Essential_Objective_Exempt_Count INT,
    Essential_Objective_Started_Count INT,
    Exempt_Role_Status VARCHAR(100),
    First_Trainee_Login_Date DATE,
    First_Update_Date DATE,
    First_Update_Date_Year INT,
    Last_Trainee_Login_Date DATE,
    Last_Update_Date DATE,
    Number_Of_Months_Remaining INT,
    Objective_1_Element_Count INT,
    Objective_1_State VARCHAR(100),
    Objective_1_State_Date DATE,
    Objective_2_Element_Count INT,
    Objective_2_State VARCHAR(100),
    Objective_2_State_Date DATE,
    Objective_3_Element_Count INT,
    Objective_3_State VARCHAR(100),
    Objective_3_State_Date DATE,
    Objective_4_Element_Count INT,
    Objective_4_State VARCHAR(100),
    Objective_4_State_Date DATE,
    Objective_5_Element_Count INT,
    Objective_5_State VARCHAR(100),
    Objective_5_State_Date DATE,
    Objective_6_Element_Count INT,
    Objective_6_State VARCHAR(100),
    Objective_6_State_Date DATE,
    Objective_7_Element_Count INT,
    Objective_7_State VARCHAR(100),
    Objective_7_State_Date DATE,
    Objective_8_Element_Count INT,
    Objective_8_State VARCHAR(100),
    Objective_8_State_Date DATE,
    Objective_9_Element_Count INT,
    Objective_9_State VARCHAR(100),
    Objective_9_State_Date DATE,
    Objective_10_Element_Count INT,
    Objective_10_State VARCHAR(100),
    Objective_10_State_Date DATE,
    Objective_11_Element_Count INT,
    Objective_11_State VARCHAR(100),
    Objective_11_State_Date DATE,
    Objective_12_Element_Count INT,
    Objective_12_State VARCHAR(100),
    Objective_12_State_Date DATE,
    Objective_13_Element_Count INT,
    Objective_13_State VARCHAR(100),
    Objective_13_State_Date DATE,
    Objective_14_Element_Count INT,
    Objective_14_State VARCHAR(100),
    Objective_14_State_Date DATE,
    Objective_15_Element_Count INT,
    Objective_15_State VARCHAR(100),
    Objective_15_State_Date DATE,
    Objective_16_Element_Count INT,
    Objective_16_State VARCHAR(100),
    Objective_16_State_Date DATE,
    Objective_17_Element_Count INT,
    Objective_17_State VARCHAR(100),
    Objective_17_State_Date DATE,
    Objective_18_Element_Count INT,
    Objective_18_State VARCHAR(100),
    Objective_18_State_Date DATE,
    Objective_19_Element_Count INT,
    Objective_19_State VARCHAR(100),
    Objective_19_State_Date DATE,
    Objective_20_Element_Count INT,
    Objective_20_State VARCHAR(100),
    Objective_20_State_Date DATE,
    Objective_21_Element_Count INT,
    Objective_21_State VARCHAR(100),
    Objective_21_State_Date DATE,
    Objective_22_Element_Count INT,
    Objective_22_State VARCHAR(100),
    Objective_22_State_Date DATE,
    Objective_23_Element_Count INT,
    Objective_23_State VARCHAR(100),
    Objective_23_State_Date DATE,
    Objective_24_Element_Count INT,
    Objective_24_State VARCHAR(100),
    Objective_24_State_Date DATE,
    Optional_Objectives_Remaining INT,
    Progress_Recorded INT,
    Progress_Approved INT,
    Required_Objectives_Available INT,
    Role_Count INT,
    Time_Calculated_Approved_Employer INT,
    Time_Calculated_On_Role INT,
    Time_Units_Claimed INT,
    Time_Units_Claimed_Student_Affiliate INT,
    Time_Units_Approved INT,
    Time_Units_Approved_Student_Affiliate INT,
    Total_Objectives_Remaining INT,
    Zero_Percent_Relevant_Role VARCHAR(100),
    Trainees_Report_Data VARCHAR(100),
    Member_Active_Pathway_ID VARCHAR(100),
    Optional_Objectives_Approved_Count INT,
    Optional_Objectives_Exempt_Count INT,
    Optional_Objectives_Progress_Count INT,
    Optional_Objectives_Started_Count INT,
    ingestedDate DATE,
    AXIA_AccaID VARCHAR(100)
) AS [result]'

EXEC (@DynamicSQL)

--B2C_Role_History
SET @DynamicSQL = '
CREATE OR ALTER VIEW [dbo].[B2C_Role_History] AS
SELECT
B2C_Role_History_SK,
Contact_Reference,
D365CE_Relationship_Role,
Relationship_Status,
Relationship_Type,
Relationship_Start_Date,
Relationship_End_Date,
Role_Status,
Role_Type,
Role_Start_Date,
Role_End_Date,
Primary_YN,
Action_Type,
Action_Reason,
Relationship_Start_Date_Year,
CreatedOn,
ModifiedOn,
Alternative_Reference,
Action_Code,
Action_Route,
Action_Description,
Role_Group
FROM OPENROWSET (
    BULK ''' + @CuratedContainerName + '/BusinessDataModelDataset/B2C/Customer/B2C_Role_History/'',
    DATA_SOURCE = ''DataLakeDataSource'',
    FORMAT = ''delta''
) WITH (
B2C_Role_History_SK VARCHAR(100),
Contact_Reference VARCHAR(100),
D365CE_Relationship_Role VARCHAR(100),
Relationship_Status VARCHAR(4000),
Relationship_Type VARCHAR(100),
Relationship_Start_Date DATE,
Relationship_End_Date DATE,
Role_Status VARCHAR(4000),
Role_Type VARCHAR(100),
Role_Start_Date DATE,
Role_End_Date DATE,
Primary_YN VARCHAR(100),
Action_Type VARCHAR(4000),
Action_Reason VARCHAR(100),
Relationship_Start_Date_Year INT,
CreatedOn DATETIME,
ModifiedOn DATETIME,
Alternative_Reference VARCHAR(100),
Action_Code VARCHAR(100),
Action_Route VARCHAR(100),
Action_Description VARCHAR(4000),
Role_Group VARCHAR(100)
) AS [result]'
EXEC (@DynamicSQL)


--B2C_Student_Role_History
SET @DynamicSQL = 'CREATE OR ALTER VIEW [dbo].[B2C_Student_Role_History] AS
SELECT
B2C_Student_Role_History_SK,
Contact_Reference,
D365CE_Relationship_Role,
B2C_FASSET_SK,
Qualification_Code,
Qualification_Description,
Role_Status,
Role_Start_Date,
Role_End_Date,
Active_YN,
Registration_Date,
Auto_Transfer_FIA_To_ACCA,
Switching_Qualification_Preference,
Action_Type,
Action_Reason,
SQA_Eligible_Date,
Oxford_Brookes_Preference,
Role_Start_Date_Year,
CreatedOn,
ModifiedOn,
B2C_Role_History_SK,
Alternative_Reference,
Passed_Finalist_YN
FROM OPENROWSET (
    BULK ''' + @CuratedContainerName + '/BusinessDataModelDataset/B2C/Customer/B2C_Student_Role_History/'',
    DATA_SOURCE = ''DataLakeDataSource'',
    FORMAT = ''delta''
) WITH (
B2C_Student_Role_History_SK VARCHAR(100),
Contact_Reference VARCHAR(100),
D365CE_Relationship_Role VARCHAR(100),
B2C_FASSET_SK VARCHAR(100),
Qualification_Code VARCHAR(100),
Qualification_Description VARCHAR(100),
Role_Status VARCHAR(4000),
Role_Start_Date DATE,
Role_End_Date DATE,
Active_YN VARCHAR(100),
Registration_Date DATE,
Auto_Transfer_FIA_To_ACCA VARCHAR(4000),
Switching_Qualification_Preference VARCHAR(100),
Action_Type VARCHAR(4000),
Action_Reason VARCHAR(100),
SQA_Eligible_Date DATE,
Oxford_Brookes_Preference VARCHAR(4000),
Role_Start_Date_Year INT,
CreatedOn DATETIME,
ModifiedOn DATETIME,
B2C_Role_History_SK VARCHAR(100),
Alternative_Reference VARCHAR(100),
Passed_Finalist_YN VARCHAR(100)
) AS [result]'
EXEC (@DynamicSQL)

--B2C_Exemption_Offer
SET @DynamicSQL = 'CREATE OR ALTER VIEW [dbo].[B2C_Exemption_Offer] AS
SELECT
B2C_Exemption_Offer_SK,
Contact_Reference,
EAC_Exemption_Subject_SK,
EAC_Institution_SK,
EAC_National_Qualification_SK,
Award_Expected,
Certificate_Number,
Conditional_YN,
Conditional_Conversion_Date,
Conditional_Expiry_Date,
Date_Accepted,
Education_Assessment,
Education_Assessment_Date,
Eligible_Date,
Exemption_Subject,
Exemption_Accreditation,
Exemption_Status,
Exemption_Type,
Exemption_Type_Code,
Exemption_Type_Classification,
Forfeit_Refund_Status,
Free_Of_Charge_YN,
Graduation_Date,
Institution,
National_Qualification,
Programme,
Registration_Entry_IR_YN,
Subject_Major,
Type,
Created_By,
Eligible_Date_Year,
CreatedOn,
ModifiedOn,
EAC_Available_Accreditation_SK,
EAC_Programme_SK,
EAC_Subject_Major_SK,
Forfeit_Reason,
Forfeit_Description,
B2C_Exemption_Forfeit_SK
FROM OPENROWSET (
    BULK ''' + @CuratedContainerName + '/BusinessDataModelDataset/B2C/Customer/B2C_Exemption_Offer/'',
    DATA_SOURCE = ''DataLakeDataSource'',
    FORMAT = ''delta''
) WITH (
B2C_Exemption_Offer_SK VARCHAR(100),
Contact_Reference VARCHAR(100),
EAC_Exemption_Subject_SK VARCHAR(100),
EAC_Institution_SK VARCHAR(100),
EAC_National_Qualification_SK VARCHAR(100),
Award_Expected VARCHAR(4000),
Certificate_Number VARCHAR(100),
Conditional_YN VARCHAR(100),
Conditional_Conversion_Date DATE,
Conditional_Expiry_Date DATE,
Date_Accepted DATE,
Education_Assessment VARCHAR(850),
Education_Assessment_Date DATE,
Eligible_Date DATE,
Exemption_Subject VARCHAR(100),
Exemption_Accreditation VARCHAR(2000),
Exemption_Status VARCHAR(4000),
Exemption_Type VARCHAR(850),
Exemption_Type_Code VARCHAR(100),
Exemption_Type_Classification VARCHAR(4000),
Forfeit_Refund_Status VARCHAR(4000),
Free_Of_Charge_YN VARCHAR(100),
Graduation_Date DATE,
Institution VARCHAR(400),
National_Qualification VARCHAR(400),
Programme VARCHAR(400),
Registration_Entry_IR_YN VARCHAR(100),
Subject_Major VARCHAR(400),
Type VARCHAR(4000),
Created_By VARCHAR(100),
Eligible_Date_Year INT,
CreatedOn DATETIME,
ModifiedOn DATETIME,
EAC_Available_Accreditation_SK VARCHAR(100),
EAC_Programme_SK VARCHAR(100),
EAC_Subject_Major_SK VARCHAR(100),
Forfeit_Reason VARCHAR(1000),
Forfeit_Description VARCHAR(4000),
B2C_Exemption_Forfeit_SK VARCHAR(100)
) AS [result]'
EXEC (@DynamicSQL)

--B2C_Member_Role_History
SET @DynamicSQL = 'CREATE OR ALTER VIEW [dbo].[B2C_Member_Role_History] AS
SELECT
B2C_Member_Role_History_SK,
D365CE_Relationship_Role,
B2C_South_African_Qualifications_Authority_SK,
Contact_Reference,
Member_Role,
Role_Status,
Role_Start_Date,
Role_End_Date,
Active_YN,
CPD_Start_Date,
Directory_Of_Members,
In_Practice_YN,
Membership_Date,
Fellow_Due_Date,
Fellow_Date,
Lifetime_Member_Date,
Action_Type,
Action_Reason,
Membership_Year,
CreatedOn,
ModifiedOn,
B2C_Role_History_SK
FROM OPENROWSET (
    BULK ''' + @CuratedContainerName + '/BusinessDataModelDataset/B2C/Customer/B2C_Member_Role_History/'',
    DATA_SOURCE = ''DataLakeDataSource'',
    FORMAT = ''delta''
) WITH (
B2C_Member_Role_History_SK VARCHAR(100),
D365CE_Relationship_Role VARCHAR(100),
B2C_South_African_Qualifications_Authority_SK VARCHAR(100),
Contact_Reference VARCHAR(100),
Member_Role VARCHAR(100),
Role_Status VARCHAR(4000),
Role_Start_Date DATE,
Role_End_Date DATE,
Active_YN VARCHAR(100),
CPD_Start_Date DATE,
Directory_Of_Members VARCHAR(100),
In_Practice_YN VARCHAR(100),
Membership_Date DATE,
Fellow_Due_Date DATE,
Fellow_Date DATE,
Lifetime_Member_Date DATE,
Action_Type VARCHAR(4000),
Action_Reason VARCHAR(100),
Membership_Year INT,
CreatedOn DATETIME,
ModifiedOn DATETIME,
B2C_Role_History_SK VARCHAR(100)
) AS [result]'
EXEC (@DynamicSQL)

--B2C_Affiliate_Role_History
SET @DynamicSQL = 'CREATE OR ALTER VIEW [dbo].[B2C_Affiliate_Role_History] AS
SELECT
B2C_Affiliate_Role_History_SK,
Contact_Reference,
D365CE_Relationship_Role,
B2C_FASSET_SK,
Affiliate_Role,
Role_Status,
Role_Start_Date,
Role_End_Date,
Active_YN,
Affiliate_Date,
Long_Term_Affiliate_Date,
Long_Term_Affiliate_Due_Date,
Action_Type,
Action_Reason,
Affiliate_List_YN,
Role_Start_Date_Year,
CreatedOn,
ModifiedOn,
B2C_Role_History_SK
FROM OPENROWSET (
    BULK ''' + @CuratedContainerName + '/BusinessDataModelDataset/B2C/Customer/B2C_Affiliate_Role_History/'',
    DATA_SOURCE = ''DataLakeDataSource'',
    FORMAT = ''delta''
) WITH (
B2C_Affiliate_Role_History_SK VARCHAR(100),
Contact_Reference VARCHAR(100),
D365CE_Relationship_Role VARCHAR(100),
B2C_FASSET_SK VARCHAR(100),
Affiliate_Role VARCHAR(100),
Role_Status VARCHAR(4000),
Role_Start_Date DATE,
Role_End_Date DATE,
Active_YN VARCHAR(100),
Affiliate_Date DATE,
Long_Term_Affiliate_Date DATE,
Long_Term_Affiliate_Due_Date DATE,
Action_Type VARCHAR(4000),
Action_Reason VARCHAR(100),
Affiliate_List_YN VARCHAR(100),
Role_Start_Date_Year INT,
CreatedOn DATETIME,
ModifiedOn DATETIME,
B2C_Role_History_SK VARCHAR(100)
) AS [result]'
EXEC (@DynamicSQL)

--B2C_Transfer
SET @DynamicSQL = 'CREATE OR ALTER VIEW [dbo].[B2C_Transfer] AS
SELECT
B2C_Transfer_SK,
Contact_Reference,
Transfer_Code,
Transfer_Name,
Transfer_Date,
Role_Transfer_Failure_Error,
CreatedOn_Year,
CreatedOn,
ModifiedOn
FROM OPENROWSET (
    BULK ''' + @CuratedContainerName + '/BusinessDataModelDataset/B2C/Customer/B2C_Transfer/'',
    DATA_SOURCE = ''DataLakeDataSource'',
    FORMAT = ''delta''
) WITH (
B2C_Transfer_SK VARCHAR(100),
Contact_Reference VARCHAR(100),
Transfer_Code VARCHAR(100),
Transfer_Name VARCHAR(100),
Transfer_Date DATETIME,
Role_Transfer_Failure_Error VARCHAR(1000),
CreatedOn_Year INT,
CreatedOn DATETIME,
ModifiedOn DATETIME
) AS [result]'
EXEC (@DynamicSQL)

--B2C_Exemption_Forfeit
SET @DynamicSQL = 'CREATE OR ALTER VIEW [dbo].[B2C_Exemption_Forfeit] AS
SELECT
B2C_Exemption_Forfeit_SK,
APP_Application_SK,
Forfeit_Reason,
Forfeit_Description,
CreatedOn_Year,
CreatedOn,
ModifiedOn
FROM OPENROWSET (
    BULK ''' + @CuratedContainerName + '/BusinessDataModelDataset/B2C/Customer/B2C_Exemption_Forfeit/'',
    DATA_SOURCE = ''DataLakeDataSource'',
    FORMAT = ''delta''
) WITH (
B2C_Exemption_Forfeit_SK VARCHAR(100),
APP_Application_SK VARCHAR(100),
Forfeit_Reason VARCHAR(100),
Forfeit_Description VARCHAR(5000),
CreatedOn_Year INT,
CreatedOn DATETIME,
ModifiedOn DATETIME
) AS [result]'

EXEC (@DynamicSQL)

--B2C_Employment
SET @DynamicSQL = 'CREATE OR ALTER VIEW [dbo].[B2C_Employment] AS
SELECT
Contact_Reference,
Employer,
Job_Title,
Organisation_Industry,
Created_On_Year,
CreatedOn,
ModifiedOn,
Organisation_Sector,
Department,
Employment_Status,
Employer_Organisation_Size
FROM OPENROWSET (
    BULK ''' + @CuratedContainerName + '/BusinessDataModelDataset/B2C/Customer/B2C_Employment/'',
    DATA_SOURCE = ''DataLakeDataSource'',
    FORMAT = ''delta''
) WITH (
Contact_Reference VARCHAR(100),
Employer VARCHAR(1000),
Job_Title VARCHAR(100),
Organisation_Industry VARCHAR(4000),
Created_On_Year INT,
CreatedOn DATETIME,
ModifiedOn DATETIME,
Organisation_Sector VARCHAR(4000),
Department VARCHAR(100),
Employment_Status VARCHAR(4000),
Employer_Organisation_Size VARCHAR(4000)
) AS [result]'
EXEC (@DynamicSQL)

--B2C_South_African_Qualification_Authority
SET @DynamicSQL = 'CREATE OR ALTER VIEW [dbo].[B2C_South_African_Qualification_Authority] AS
SELECT
B2C_South_African_Qualification_Authority_SK,
Contact_Reference,
D365CE_Contact,
South_African_ID_Number,
Alternate_ID_Number,
Alternate_ID_Type,
Citizen_Resident_Status,
Disability,
Employment_Status,
Ethnicity,
Geographic_Area_of_Residence,
Home_Language,
Nationality,
Communicating,
Hearing,
Remembering,
Seeing,
Self_Care,
Walking,
Last_Updated,
CreatedOn_Year,
CreatedOn,
ModifiedOn,
Created_By,
Modified_By
FROM OPENROWSET (
    BULK ''' + @CuratedContainerName + '/BusinessDataModelDataset/B2C/Customer/B2C_South_African_Qualification_Authority/'',
    DATA_SOURCE = ''DataLakeDataSource'',
    FORMAT = ''delta''
) WITH (
B2C_South_African_Qualification_Authority_SK VARCHAR(100),
Contact_Reference VARCHAR(100),
D365CE_Contact VARCHAR(100),
South_African_ID_Number VARCHAR(100),
Alternate_ID_Number VARCHAR(100),
Alternate_ID_Type VARCHAR(4000),
Citizen_Resident_Status VARCHAR(4000),
Disability VARCHAR(4000),
Employment_Status VARCHAR(4000),
Ethnicity VARCHAR(4000),
Geographic_Area_of_Residence VARCHAR(4000),
Home_Language VARCHAR(4000),
Nationality VARCHAR(4000),
Communicating VARCHAR(4000),
Hearing VARCHAR(4000),
Remembering VARCHAR(4000),
Seeing VARCHAR(4000),
Self_Care VARCHAR(4000),
Walking VARCHAR(4000),
Last_Updated DATETIME,
CreatedOn_Year INT,
CreatedOn DATETIME,
ModifiedOn DATETIME,
Created_By VARCHAR(100),
Modified_By VARCHAR(100)
) AS [result]'
EXEC (@DynamicSQL)

--B2C_FASSET
SET @DynamicSQL = 'CREATE OR ALTER VIEW [dbo].[B2C_FASSET] AS
SELECT
B2C_FASSET_SK,
Contact_Reference,
D365CE_Contact,
South_African_ID_Number,
Alternate_ID_Number,
Alternate_ID_Type,
Citizen_Resident_Status,
Employment_Status,
Ethnicity,
Geographic_Area_of_Residence,
Home_Language,
Matriculated_YN,
Matriculated_Municipality,
Matriculated_Postal_Code,
Matriculated_Town_City,
Municipality,
Nationality,
Communicating,
Hearing,
Remembering,
Seeing,
Self_Care,
Walking,
Are_You_Undertaking_Your_ACCA_Studies_As_A_Learnership_YN,
Learning_Programme_Code,
Date_Obtained_Qualification,
CreatedOn_Year,
CreatedOn,
ModifiedOn,
Matriculated_Province
FROM OPENROWSET (
    BULK ''' + @CuratedContainerName + '/BusinessDataModelDataset/B2C/Customer/B2C_FASSET/'',
    DATA_SOURCE = ''DataLakeDataSource'',
    FORMAT = ''delta''
) WITH (
B2C_FASSET_SK VARCHAR(160),
Contact_Reference VARCHAR(100),
D365CE_Contact VARCHAR(100),
South_African_ID_Number VARCHAR(100),
Alternate_ID_Number VARCHAR(100),
Alternate_ID_Type VARCHAR(4000),
Citizen_Resident_Status VARCHAR(4000),
Employment_Status VARCHAR(4000),
Ethnicity VARCHAR(4000),
Geographic_Area_of_Residence VARCHAR(4000),
Home_Language VARCHAR(4000),
Matriculated_YN VARCHAR(100),
Matriculated_Municipality VARCHAR(850),
Matriculated_Postal_Code VARCHAR(100),
Matriculated_Town_City VARCHAR(100),
Municipality VARCHAR(850),
Nationality VARCHAR(4000),
Communicating VARCHAR(4000),
Hearing VARCHAR(4000),
Remembering VARCHAR(4000),
Seeing VARCHAR(4000),
Self_Care VARCHAR(4000),
Walking VARCHAR(4000),
Are_You_Undertaking_Your_ACCA_Studies_As_A_Learnership_YN VARCHAR(100),
Learning_Programme_Code VARCHAR(100),
Date_Obtained_Qualification VARCHAR(100),
CreatedOn_Year INT,
CreatedOn DATETIME,
ModifiedOn DATETIME,
Matriculated_Province VARCHAR(4000)
) AS [result]'
EXEC (@DynamicSQL)

--B2C_Registration_Code
SET @DynamicSQL = 'CREATE OR ALTER VIEW [dbo].[B2C_Registration_Code] AS
SELECT
B2C_Registration_Code_SK,
B2B_Registration_Code_SK,
Contact_Reference,
Code,
Status,
CreatedOn_Year,
CreatedOn,
ModifiedOn
FROM OPENROWSET (
    BULK ''' + @CuratedContainerName + '/BusinessDataModelDataset/B2C/Customer/B2C_Registration_Code/'',
    DATA_SOURCE = ''DataLakeDataSource'',
    FORMAT = ''delta''
) WITH (
B2C_Registration_Code_SK VARCHAR(100),
B2B_Registration_Code_SK VARCHAR(100),
Contact_Reference VARCHAR(100),
Code VARCHAR(850),
Status VARCHAR(4000),
CreatedOn_Year INT,
CreatedOn DATETIME,
ModifiedOn DATETIME
) AS [result]'
EXEC (@DynamicSQL)