USE BusinessDataModelDataset;
GO 

DECLARE @CuratedContainerName varchar(255) = 'curated'
-------------------------------------------------------------------------------------------------------------
--Copy and paste from below into the script activity. Uncomment variable declaration section.
/*
DECLARE @CuratedContainerName varchar(255) = @CuratedContainerName_Input
*/
 
DECLARE @DynamicSQL nvarchar(4000) --Must be of type nvarchar as sp_executesql doesn't accept varchar type
DECLARE @DynamicSQL1 nvarchar(4000) --Must be of type nvarchar as sp_executesql doesn't accept varchar type
 
--Check if the database already exists
--B2B_Approved_Employer

SET @DynamicSQL = 'CREATE OR ALTER VIEW [dbo].[B2B_Approved_Employer] AS
SELECT
B2B_Approved_Employer_SK,
Stream_ID_AQD,
Stream_ID_PCD,
Stream_ID_PD,
Stream_ID_TD,
Stream_ID_SA,
Account_Number,
Approval_Scope_AQD,
Approval_Scope_PCD,
Approval_Scope_PD,
Approval_Scope_TD,
Approval_Scope_SA,
Approval_Sub_Scope_AQD,
Approval_Sub_Scope_PCD,
Approval_Sub_Scope_PD,
Approval_Sub_Scope_TD,
Approval_Sub_Scope_SA,
Approval_Valid_Until_AQD,
Approval_Valid_Until_PCD,
Approval_Valid_Until_PD,
Approval_Valid_Until_TD,
Approval_Valid_Until_SA,
Approved_Streams,
Audit_Experience_Risk_YN,
FPER_Exemption_YN,
Include_In_Directory_YN,
Other_Supervisory_Body,
Part_Dir_Involved_In_Training_Dev_And_Appraisal_YN,
Partner_Body,
PO_Exemption_YN,
Recognised_Supervisory_Body,
Recommendations_AQD,
Recommendations_PCD,
Recommendations_PD,
Recommendations_TD,
Recommendations_SA,
Registry_ID_AQD,
Registry_ID_PCD,
Registry_ID_PD,
Registry_ID_TD,
Registry_ID_SA,
Renewal_Date_AQD,
Renewal_Date_PCD,
Renewal_Date_PD,
Renewal_Date_TD,
Subsidiaries_Included_In_Approval_AQD_YN,
Subsidiaries_Included_In_Approval_PCD_YN,
Subsidiaries_Included_In_Approval_PD_YN,
Subsidiaries_Included_In_Approval_TD_YN,
Training_Principal_IRBA_Registration_Number,
Account_Manager_AQD,
Account_Manager_PCD,
Account_Manager_PD,
Account_Manager_TD,
Account_Manager_SA,
Monitoring_Due_Date_AQD,
Monitoring_Due_Date_PCD,
Monitoring_Due_Date_PD,
Monitoring_Due_Date_TD,
Monitoring_Due_Date_SA,
Status,
Organisation_Sector,
Employees_In_Organisation,
Directors_Partners_In_Organisation,
Number_Of_Clients,
Number_Of_Audit_Clients,
Number_Of_ACCA_Trainees,
Number_Of_ACCA_Members,
IRBA_Number,
Approval_Comments_AQD,
Approval_Comments_PCD,
Approval_Comments_PD,
Approval_Comments_TD,
Approval_Comments_SA,
Employers_ACCA_Grade,
PCD_Directory_Preference_YN,
CreatedOn_Year,
CreatedOn,
ModifiedOn,
Renewal_Date_SA,
B2B_Customer_SK,
Subsidiaries_Included_In_Approval_SA_YN'

SET @DynamicSQL1 =
' FROM OPENROWSET (
    BULK ''' + @CuratedContainerName + '/BusinessDataModelDataset/B2B/Approved_Employer/B2B_Approved_Employer/'',
    DATA_SOURCE = ''DataLakeDataSource'',
    FORMAT = ''delta''
) WITH (
B2B_Approved_Employer_SK VARCHAR(100),
Stream_ID_AQD VARCHAR(100),
Stream_ID_PCD VARCHAR(100),
Stream_ID_PD VARCHAR(100),
Stream_ID_TD VARCHAR(100),
Stream_ID_SA VARCHAR(100),
Account_Number VARCHAR(100),
Approval_Scope_AQD VARCHAR(4000),
Approval_Scope_PCD VARCHAR(4000),
Approval_Scope_PD VARCHAR(4000),
Approval_Scope_TD VARCHAR(4000),
Approval_Scope_SA VARCHAR(4000),
Approval_Sub_Scope_AQD VARCHAR(4000),
Approval_Sub_Scope_PCD VARCHAR(4000),
Approval_Sub_Scope_PD VARCHAR(4000),
Approval_Sub_Scope_TD VARCHAR(4000),
Approval_Sub_Scope_SA VARCHAR(4000),
Approval_Valid_Until_AQD DATE,
Approval_Valid_Until_PCD DATE,
Approval_Valid_Until_PD DATE,
Approval_Valid_Until_TD DATE,
Approval_Valid_Until_SA DATE,
Approved_Streams VARCHAR(4000),
Audit_Experience_Risk_YN VARCHAR(100),
FPER_Exemption_YN VARCHAR(100),
Include_In_Directory_YN VARCHAR(100),
Other_Supervisory_Body VARCHAR(100),
Part_Dir_Involved_In_Training_Dev_And_Appraisal_YN VARCHAR(100),
Partner_Body VARCHAR(4000),
PO_Exemption_YN VARCHAR(100),
Recognised_Supervisory_Body VARCHAR(4000),
Recommendations_AQD VARCHAR(2000),
Recommendations_PCD VARCHAR(2000),
Recommendations_PD VARCHAR(2000),
Recommendations_TD VARCHAR(2000),
Recommendations_SA VARCHAR(2000),
Registry_ID_AQD VARCHAR(100),
Registry_ID_PCD VARCHAR(100),
Registry_ID_PD VARCHAR(100),
Registry_ID_TD VARCHAR(100),
Registry_ID_SA VARCHAR(100),
Renewal_Date_AQD DATE,
Renewal_Date_PCD DATE,
Renewal_Date_PD DATE,
Renewal_Date_TD DATE,
Subsidiaries_Included_In_Approval_AQD_YN VARCHAR(100),
Subsidiaries_Included_In_Approval_PCD_YN VARCHAR(100),
Subsidiaries_Included_In_Approval_PD_YN VARCHAR(100),
Subsidiaries_Included_In_Approval_TD_YN VARCHAR(100),
Training_Principal_IRBA_Registration_Number VARCHAR(100),
Account_Manager_AQD VARCHAR(100),
Account_Manager_PCD VARCHAR(100),
Account_Manager_PD VARCHAR(100),
Account_Manager_TD VARCHAR(100),
Account_Manager_SA VARCHAR(100),
Monitoring_Due_Date_AQD DATE,
Monitoring_Due_Date_PCD DATE,
Monitoring_Due_Date_PD DATE,
Monitoring_Due_Date_TD DATE,
Monitoring_Due_Date_SA DATE,
Status VARCHAR(4000),
Organisation_Sector VARCHAR(4000),
Employees_In_Organisation VARCHAR(4000),
Directors_Partners_In_Organisation VARCHAR(4000),
Number_Of_Clients INT,
Number_Of_Audit_Clients INT,
Number_Of_ACCA_Trainees VARCHAR(4000),
Number_Of_ACCA_Members VARCHAR(4000),
IRBA_Number VARCHAR(100),
Approval_Comments_AQD VARCHAR(2000),
Approval_Comments_PCD VARCHAR(2000),
Approval_Comments_PD VARCHAR(2000),
Approval_Comments_TD VARCHAR(2000),
Approval_Comments_SA VARCHAR(2000),
Employers_ACCA_Grade VARCHAR(4000),
PCD_Directory_Preference_YN VARCHAR(100),
CreatedOn_Year INT,
CreatedOn DATETIME,
ModifiedOn DATETIME,
Renewal_Date_SA DATE,
B2B_Customer_SK VARCHAR(100),
Subsidiaries_Included_In_Approval_SA_YN VARCHAR(100)
) AS [result]'
EXEC (@DynamicSQL + @DynamicSQL1)

--B2B_Application_Contact
SET @DynamicSQL = 'CREATE OR ALTER VIEW [dbo].[B2B_Application_Contact] AS
SELECT
B2B_Application_Contact_SK,
APP_Application_SK,
Contact_Reference,
Account_Number,
Professional_Qualification,
Email_Address,
First_Name,
Last_Name,
Contact_Type,
Job_Title,
Telephone_Number,
Title,
CreatedOn_Year,
CreatedOn,
ModifiedOn,
B2B_Customer_SK
FROM OPENROWSET (
    BULK ''' + @CuratedContainerName + '/BusinessDataModelDataset/B2B/Approved_Employer/B2B_Application_Contact/'',
    DATA_SOURCE = ''DataLakeDataSource'',
    FORMAT = ''delta''
) WITH (
B2B_Application_Contact_SK VARCHAR(100),
APP_Application_SK VARCHAR(100),
Contact_Reference VARCHAR(100),
Account_Number VARCHAR(100),
Professional_Qualification VARCHAR(MAX),
Email_Address VARCHAR(100),
First_Name VARCHAR(100),
Last_Name VARCHAR(100),
Contact_Type VARCHAR(100),
Job_Title VARCHAR(100),
Telephone_Number VARCHAR(100),
Title VARCHAR(100),
CreatedOn_Year INT,
CreatedOn DATETIME,
ModifiedOn DATETIME,
B2B_Customer_SK VARCHAR(100)
) AS [result]'
EXEC (@DynamicSQL)

--B2B_Approved_Employer_Stream
SET @DynamicSQL = 'CREATE OR ALTER VIEW [dbo].[B2B_Approved_Employer_Stream] AS
SELECT
B2B_Approved_Employer_Stream_SK,
B2B_Approved_Employer_SK,
B2B_Customer_SK,
Account_Number,
Stream_ID,
Name,
Approval_Scope,
Approval_Sub_Scope,
Approval_Valid_Until,
Recommendations,
Registry_ID,
Renewal_Date,
Subsidiaries_Included_In_Approval_YN,
Account_Manager,
Monitoring_Due_Date,
Approval_Comments,
CreatedOn_Year,
CreatedOn,
ModifiedOn
FROM OPENROWSET (
    BULK ''' + @CuratedContainerName + '/BusinessDataModelDataset/B2B/Approved_Employer/B2B_Approved_Employer_Stream/'',
    DATA_SOURCE = ''DataLakeDataSource'',
    FORMAT = ''delta''
) WITH (
B2B_Approved_Employer_Stream_SK VARCHAR(100),
B2B_Approved_Employer_SK VARCHAR(100),
B2B_Customer_SK VARCHAR(100),
Account_Number VARCHAR(100),
Stream_ID VARCHAR(100),
Name VARCHAR(100),
Approval_Scope VARCHAR(100),
Approval_Sub_Scope VARCHAR(100),
Approval_Valid_Until DATE,
Recommendations VARCHAR(100),
Registry_ID VARCHAR(100),
Renewal_Date DATE,
Subsidiaries_Included_In_Approval_YN VARCHAR(100),
Account_Manager VARCHAR(100),
Monitoring_Due_Date DATE,
Approval_Comments VARCHAR(2000),
CreatedOn_Year INT,
CreatedOn DATETIME,
ModifiedOn DATETIME
) AS [result]'
EXEC (@DynamicSQL)